name: 'PyTest with Python3.8 - Python3.10'

on:
  pull_request_target:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8.x', '3.9.x', '3.10.x' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install maltego-trx
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip3 install .

      - name: Run PyTest
        run: |
          cd tests
          pip install -r requirements.txt
          pytest